---
version: '3'

volumes:
  nltk_data:

services:
  compute:
    image: danrasband/w266
    command: ['bash']
    ports:
      - 8896:8896 # Jupyter Notebook
      - 6006:6006 # Tensorboard
    stdin_open: true
    tty: true
    volumes:
      - .:/compute/w266
      - nltk_data:/root/nltk_data
